# Generated by Django 5.0.6 on 2024-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=30)),
            ],
        ),
    ]
