# Generated by Django 5.0.6 on 2024-06-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
